name: sam6d
channels:
  - xformers
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip
  - python=3.10.12
  - pip:
    - torch
    - torchvision
    - fvcore
    - xformers
    - torchmetrics
    - blenderproc
    - opencv-python 
    # ISM 
    - omegaconf
    - ruamel.yaml
    - hydra-colorlog
    - hydra-core
    - gdown
    - pandas
    - imageio
    - pyrender
    - pytorch-lightning
    - pycocotools 
    - distinctipy
    - git+https://github.com/facebookresearch/segment-anything.git  # SAM
    - git+https://github.com/facebookresearch/sam2.git  # SAM2
    - ultralytics # FastSAM
    # PEM
    - timm
    - gorilla-core
    - trimesh
    - gpustat
    - imgaug
    - einops